version: '3.4'

x-mcserver-common:
  &default-mcserver
  build: 
   context: .
   args:
    INSTALLERURL: ${INSTALLERURL:-https://minecraft.azureedge.net/bin-linux/bedrock-server-1.13.0.34.zip}
  image: ${DOCKERIMAGENAME:-karlrees/docker_bedrockserver}
  volumes:
  - ${MCVOLUME:-./config}:/config
  restart: always
  stdin_open: true
  tty: true

networks:
 default:
  driver: macvlan
  driver_opts:
   parent: ${NETWORKINTERFACE:-eth0}
  ipam:
   config:
   - subnet: ${IPPREFIX:-192.168.0}.0/24

#for each server, copy and paste one of the example servers
#be sure to change the name and last three digits of IP address

services:
 
 #first server
 minecraft1:
  << : *default-mcserver
  environment:
   WORLD: minecraft1   
  container_name: minecraft1
  networks: 
   default:
    ipv4_address: ${IPPREFIX:-192.168.0}.201
 
 #second server
 minecraft2:
  << : *default-mcserver
  environment:
   WORLD: minecraft2
  container_name: minecraft2
  networks: 
   default:
    ipv4_address: ${IPPREFIX:-192.168.0}.202

 #first server
 minecraft3:
  << : *default-mcserver
  environment:
   WORLD: minecraft3
   MCPROP_GAMEMODE: 1   
  container_name: minecraft3
  networks: 
   default:
    ipv4_address: ${IPPREFIX:-192.168.0}.203
 
 #second server
 minecraft4:
  << : *default-mcserver
  environment:
   WORLD: minecraft4
   #MCPROP_GAMEMODE: 1
  container_name: minecraft4
  networks: 
   default:
    ipv4_address: ${IPPREFIX:-192.168.0}.204


